[package]
name = "BluetoothDeviceNotify"
version = "0.1.0"
edition = "2024"

[dependencies]
bluer = { version = "0.17.4", features = ["full"] }
env_logger = "0.11.8"
futures = "0.3.31"
notify-rust = "4.11.7"
tokio = { version = "1.48.0", features = ["full"] }
